### ISSUE TITLE
Add donation button

### ISSUE THREAD

**Issue by spitzerd** [neo-ltex/vscode-ltex#29]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
Since I cannot contribute code, I want to donate to [unional](https://github.com/neo-ltex/vscode-ltex/commits?author=unional) to support the project.

**Describe the solution you'd like**
Please add a donate button for PayPal, Liberapay, Ko-fi or similar.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by georglauterbach** [comment]
👍🏼 I was just looking for this button! I have LT Premium and seeing this project being continued makes me happy! I want to help here, but I lack the time to contribute code as well; hence, I'd like to become a financial backer (if only with a small amount).

**Comment by spitzerd** [comment]
Solved with https://github.com/neo-ltex/.github/commit/29299e65032b8bd8d10b99218417082c22e1d366

**Comment by unional** [comment]
Thanks for the support! 🌷
