### ISSUE TITLE
When Using Custom HTTP URI, still use Local First For Faster Results

### ISSUE THREAD

**Issue by georglauterbach** [neo-ltex/vscode-ltex#38]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**

When using a custom HTTP URI (I use it because I have purchased LT Premium), the request and analysis takes a while.

**Describe the solution you'd like**

It'd be nice to show the result of the local server in the meantime to fix the errors that "non-custom" (in my case, "non-premium") can show alread.

**Describe alternatives you've considered**

I am not sure whether alternatives exist.

**Additional context**

N/A

**Comment by unional** [comment]
Thanks for opening the issue. Right now I am still at the phase of cleaning up the repositories to make it easier to contribute. Will consider adding new features after that is ready.

The original system download and install 1GB of stuff for EVERY test run... 🤦

**Comment by georglauterbach** [comment]
Closing this to keep all my issues manageable.
